import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import StyledComponentsRegistry from '../styles/StyledComponentsRegistry';
import { ThemeProvider } from 'styled-components';
import theme from '@/styles/theme';
import StylesProvider from '@/styles/StylesProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body>
        <StylesProvider>{children}</StylesProvider>
      </body>
    </html>
  );
}
