import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import StylesProvider from '@/styles/StylesProvider';
import layoutStyles from '@/app/layout.module.css';
import Header from '@/components/layout/header/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body>
        <StylesProvider>
          <Header />
          <section className={layoutStyles.section}>{children}</section>
        </StylesProvider>
      </body>
    </html>
  );
}
